sudo: required

services:
  - docker

before_install:
  - docker pull alpine:edge

install:
  - docker build -t pdnsadmin/pdnsadmin:test .
  - docker run --name pdnsadmin -d -p 80:80 pdnsadmin/pdnsadmin:test
  - docker ps -a

script:
  - curl -I $(docker inspect -f '{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}' pdnsadmin)

after_success:
  - if [ "$TRAVIS_BRANCH" == "develop" ]; then
    docker tag $(docker images | grep pdnsadmin | awk '{print $3}') pdnsadmin/pdnsadmin:dev;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push pdnsadmin/pdnsadmin:dev;
    fi
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker tag $(docker images | grep pdnsadmin | awk '{print $3}') pdnsadmin/pdnsadmin:latest;
    docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push pdnsadmin/pdnsadmin:latest;
    fi