sudo: required

services:
  - docker

before_install:
  - docker pull alpine:edge

install:
  - docker build -t pdnsadmin/pdnsadmin:test .
  - docker run --name pdnsadmin -d -p 80:80 pdnsadmin/pdnsadmin:test
  - docker ps -a

script:
  - docker exec -it pdnsadmin curl -I localhost
